swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /{userId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: User Transactions by account id API
      description: API for fetching user transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User transactions retrieved successully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid id
        "500":
          description: Internal Server Error
  /transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: User Transaction by account id API
      description: API for fetching user transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User transaction retrieved successully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid id
        "500":
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Update User Transaction by transaction id
      description: API for updating user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user transaction attributes
          required: true
          schema:
            $ref: "#/definitions/Transaction"
        - in: path
          name: transactionId
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transactions:
    type: array
    items:
      type: object
      properties:
        accountId:
          type: string
        name:
          type: string
        transactions:
          type: array
          items:
            $ref: '#/definitions/Transaction'
  Transaction:
    type: object
    properties:
      Date:
        type: string
      Description:
        type: string
      Amount:
        type: number
      Balance:
        type: string
      Category:
        type: string
      Notes:
        type: string
